name: ci

on:
  push:  
    branches:
      - "staging"

jobs:
   testwebapp:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: actions/checkout@v2
      - 
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - 
        name: test
        working-directory: gowebapp/web-api
        run: echo "success" #go test -v ./...
        
   testfilterservice:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Build and Test
      working-directory: scala/
      run: echo "success"
      #sbt "project filterJobs" test 
   testlivetail:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      - 
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      -        
        name: Testing application livetail
        working-directory: gowebapp/livetail
        run: echo "success" #go test -v ./...
   testnotification:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      - 
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      -  
        name: Testing application notification app
        working-directory: gowebapp/notification
        run: echo "success" #go test -v ./...
   buildwebapp:                 
    runs-on: ubuntu-latest
    needs: testwebapp
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push web-api
        uses: docker/build-push-action@v4
        with:
          context: ./gowebapp/web-api
          file: ./gowebapp/web-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/goweb-api:${{ github.sha }}
   buildlivetail:                 
    runs-on: ubuntu-latest
    needs: testlivetail
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push livetail
        uses: docker/build-push-action@v4
        with:
          context: ./gowebapp/livetail
          file: ./gowebapp/livetail/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/livetail:${{ github.sha }}
   buildnotification:                 
    runs-on: ubuntu-latest
    needs: testnotification
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push notification
        uses: docker/build-push-action@v4
        with:
          context: ./gowebapp/notification
          file: ./gowebapp/notification/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/notification:${{ github.sha }}
   buildflinkservice:                 
    runs-on: ubuntu-latest
    needs: testfilterservice
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push flink-cluster
        uses: docker/build-push-action@v4
        with:
          context: ./scala
          file: ./scala/flink.Dockerfile   
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flink:${{ github.sha }}
   buildfilterservice:                 
    runs-on: ubuntu-latest
    needs: testfilterservice
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push flink-cluster
        uses: docker/build-push-action@v4
        with:
          context: ./scala
          file: ./scala/Dockerfile   
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/filter-service:${{ github.sha }} 
   DeployProduction:                 
    runs-on: ubuntu-latest
    needs: [buildnotification, buildlivetail, buildwebapp, buildfilterservice, buildflinkservice]
    steps:
      -
        name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
    
      - name: Deploy the Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/microservices/helm-chart/
            ##export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            ###echo "${{ github.head_ref }}.${{ github.sha }}"
            
            ####sh /opt/microservices/scripts/staging_deploy.sh ${{ github.head_ref }}.${{ github.sha }}
            helm upgrade webapp webapp-stagingchart/ -n logfire-local --set=gowebapiDeployment.gowebapi.image.tag=${{ github.sha }} --set=livetailDeployment.livetail.image.tag=${{ github.sha }} --set=notificationDeployment.notification.image.tag=${{ github.sha }}
            helm upgrade --install filter-service filter-service/ --namespace logfire-local --set redis.host=redis-master  --set flinkCluster.host=flink-chart-flink-session-deployment-rest --set image.repository=dockercgs/filter-service:${{ github.sha }}
            helm upgrade --install flink-chart flink-chart/ --namespace logfire-local --set flink.image.repository=dockercgs/flink --set flink.image.tag=${{ github.sha }}
            helm repo add flink-operator-repo https://downloads.apache.org/flink/flink-kubernetes-operator-1.4.0/
            helm repo update
            helm upgrade --install cp-schema-registry cp-schema-registry/ --namespace logfire-local --set kafka.external=true --set kafka.address=my-cluster-kafka-brokers:9092
            helm upgrade --install flink-kubernetes-operator flink-operator-repo/flink-kubernetes-operator --namespace logfire-local
